### ISSUE TITLE
Update DAOs with new queries functions

### ISSUE THREAD

**Issue by lucamrgs** [esoprana/ProgettoWebProg2018Issues#15]
Blocked by #4

**Comment by esoprana** [comment]
Blocked by # 1 (Non possono ancora essere testate per #1)

**Comment by esoprana** [comment]
Dall'issue precedente creato da Luca(lista query da controllare):
In User:
checkUserRegisteredByEmail
getByEmail

In Notification:
getUnreadNotificationByUserId

In List:
getOwnedUserListsByUserId
getSharedWithUserListsByUserId

in Log:
getUserProductLogByIds

in Product:
getProductsInListByListId

In Shop:
getShopsByCategory
