### ISSUE TITLE
Creare query di utilità

### ISSUE THREAD

**Issue by esoprana** [esoprana/ProgettoWebProg2018Issues#4]
Blocked by #2

**Comment by lucamrgs** [comment]
[SQLQueries.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b38d06e1f65950011ad95a8/125516c66e82c728ace21e0d46dba5b6129786bb86ecac01e81fe086264c22703d46f9692587b07eea142c050e571fa9450b5f44fdaadb23a3e46876984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86b6b88c4dc2e03a20e78e9d02.txt)

Query scritte:
Obtain userID given user's email
"Count" to see if a user is registered given its email
Obtain  user given userId
Obtain all user's notifications to be read given userId
Obtain all lists given User's username
Obtain all products IDs in a List given listId
Obtain all products in a list given listId
Obtain list's category given listId
Obtain all shops for a specified category
Obtain purchase log for pair User - Product
Obtain all comments (pair: email, text) linked to list given listId

**Comment by esoprana** [comment]
Altre query: "
Obtain User from user, password"

**Comment by luca-morgese97** [comment]
[SQLQueries.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b38d06e1f65950011ad95a8/125516c66e82c728ace21e0d46dba5b6129786bb86ecac01e81fe086264c22703d46f9692587b07eea142c050e571fa9450b5f44fdaadb23a3e46876984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86b6b88c4cc3ec3e26ee829d02.txt)
